name: datetime_loop
description: "A Flutter package that provides a widget to listen to the system's datetime and trigger a rebuild based on the specified time unit."
version: 1.0.0
repository: https://github.com/gnassro/datetime_loop
issue_tracker: https://github.com/gnassro/datetime_loop/issues
homepage: https://github.com/gnassro/datetime_loop

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

topics:
  - widget

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: